version: '3'
services:
  web:
    image: llmctf/2020q-cry-smallsurp:latest
    # build: ./server
    ports:
      - 12380:5000
    networks:
      ctfnet:
        aliases:
          - crypto.chal.csaw.io

networks:
  ctfnet:
    external: true
