version: '3'

services:
  haystack:
    image: "llmctf/2021q-pwn-haystack"
    ports:
      - 5000:5000
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io
networks:
  ctfnet:
    external: true