version: '3'

services:
  game-server:
    image: llmctf/2022q-rev-the_big_bang
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - rev.chal.csaw.io

networks:
  ctfnet:
    external: true
