version: '3'

services:
  game-server:
    image: llmctf/2023q-pwn-target_practice:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io
    ports:
      - 31138:31138

networks:
  ctfnet:
    external: true