version: '3'
services:
  web:
    image: llmctf/2023f-msc-sigmaslogistics:latest
    # build: ./server
    ports:
      - 12312:3000
    networks:
      ctfnet:
        aliases:
          - mandf.csaw.io

networks:
  ctfnet:
    external: true
