version: '3'

services:
  game-server:
    image: llmctf/2021f-rev-sfc:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - rev.chal.csaw.io
    ports:
      - "12345:8000"

networks:
  ctfnet:
    external: true