version: '3'

services:
  game-server:
    image: llmctf/2023q-cry-lottery:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - crypto.chal.csaw.io
    ports:
      - 5000:5000

networks:
  ctfnet:
    external: true