version: '3'

services:
  beyond-quantum-server:
    image: llmctf/2022q-cry-beyond_quantum
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - crypto.chal.csaw.io
    ports:
      - 5000:5000

networks:
  ctfnet:
    external: true
