version: '3'
services:
  web:
    image: llmctf/2020f-web-picgram:latest
    # build: ./server
    ports:
      - 12380:8000
    networks:
      ctfnet:
        aliases:
          - web.chal.csaw.io

networks:
  ctfnet:
    external: true
