version: '3'

services:
  salt_server-server:
    image: llmctf/2022f-pwn-salt_server
    ports:
      - 8787:8787
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io

networks:
  ctfnet:
    external: true
