version: '3'

services:
  game-server:
    image: llmctf/2022q-pwn-unsafe_linking
    ports:
      - 9999:9999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io

networks:
  ctfnet:
    external: true
