version: '3'

services:
  game-server:
    image: llmctf/2023q-pwn-puffin:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io
    ports:
      - "31140:31140"

networks:
  ctfnet:
    external: true