
services:
  game-server:
    image: llmctf/2021q-web-poem_collection:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - web.chal.csaw.io
    ports:
      - "12345:80"

networks:
  ctfnet:
    external: true