version: '3'
services:
  web:
    image: llmctf/2019f-pwn-arevenge:latest
    # build: ./server
    ports:
      - 8000:8000
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io

networks:
  ctfnet:
    external: true
