version: '3'

services:
  ncore-server:
    image: llmctf/2021q-rev-ncore
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - rev.chal.csaw.io

networks:
  ctfnet:
    external: true
