version: '3'
services:
  web:
    image: llmctf/2019f-rev-wrangly:latest
    # build: ./server
    networks:
      ctfnet:
        aliases:
          - rev.chal.csaw.io

networks:
  ctfnet:
    external: true
