version: '3'

services:
  superguesser-server:
    image: llmctf/2022f-msc-super_guesser_g_me
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - misc.chal.csaw.io

networks:
  ctfnet:
    external: true
