version: '3'

services:
  gotta-crack-them-all-server:
    image: llmctf/2022q-cry-gotta_crack_them_all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - crypto.chal.csaw.io
    ports:
      - 5000:5000

networks:
  ctfnet:
    external: true
